opa = "http://127.0.0.1:8000"

[kratos]
addr = "http://kratos-public.kratos"

[service]
addr = "0.0.0.0"
ports.main = "8080"
ports.health = "2040"

[iam.service]
addr = "iam.w6d-bkd"
ports.main = "5050"
ports.health = "1040"

[kafka.producers]
notif.broker = "rpk-0.rpk.kafka.svc.cluster.local:9092,rpk-1.rpk.kafka.svc.cluster.local:9092,rpk-2.rpk.kafka.svc.cluster.local:9092"
notif.topic = "notif"
error.broker = "rpk-0.rpk.kafka.svc.cluster.local:9092,rpk-1.rpk.kafka.svc.cluster.local:9092,rpk-2.rpk.kafka.svc.cluster.local:9092"
error.topic = "error"
