apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- token.yaml
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config.toml
  name: sirius-config
images:
- name: w6dio/sirius
  newName: w6dio/sirius
  newTag: v0.3.9
