apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      application: sirius

namespace: w6d-bkd

patches:
- path: opa/sidecar.yaml
  target:
    kind: Deployment
    name: sirius
    group: apps
    version: v1


resources:
- base
- opa
