apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      application: sirius

namespace: w6d-bkd

resources:
- ingress.yaml
- ../../base
- ../../opa

patches:
  - path: sidecar.yaml
    target:
      kind: Deployment
      name: sirius
      group: apps
      version: v1
