apiVersion: apps/v1
kind: Deployment
metadata:
  name: sirius
spec:
  template:
    spec:
      containers:
        - name: opa
          image: w6dio/opa
          imagePullPolicy: Always
          env:
            - name: CONFIG_OPA
              value: /data/opa/config.toml
            - name: OPA_POLICY
              value: /data/opa/acl.rego
            - name: OPA_QUERY
              value: data.map.rbac.main
          volumeMounts:
            - mountPath: /data/opa
              name: config-opa
              readOnly: true
      volumes:
        - configMap:
            defaultMode: 420
            name: sirius-opa-config
          name: config-opa